CREATE DATABASE clients;
use clients;

create table clients (
ID INT PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(25),
SURNAME VARCHAR(25)
);

ALTER TABLE clients ADD COLUMN PASSWORD_FIELD VARCHAR(20) NOT NULL AFTER SURNAME;
ALTER TABLE clients DROP password;

DELETE FROM clients WHERE ID = 1 OR ID = 2 OR ID = 3 OR ID = 4 OR ID = 5 OR ID = 6 OR ID = 7 OR ID = 8 OR ID = 9 OR ID = 10 OR ID = 11 OR ID = 12 OR ID = 13 OR ID =14;
SELECT * FROM clients;
SELECT * FROM clients WHERE FIRST_NAME='Иван' AND SURNAME = 'Иванов' AND PASSWORD_FIELD = '123456';
ALTER TABLE clients AUTO_INCREMENT = 1;
insert into clients (FIRST_NAME, SURNAME) values ("123","456"); 